spring:
  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:3000
    graphiql:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password123
      database: dev
      authentication-database: admin
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1 hour