spring:
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password123
      database: dev
      authentication-database: admin